path:
  train_path: ./data/raw_data/train.csv
  test_path: ./data/raw_data/train.csv
  predict_path: ./data/raw_data/test_data.csv
  save_path: saved_models/
  ckpt_path: # 훈련 재개 시 load할 checkpoint 위치. 처음부터 훈련 시 비워두기

dataloader:
  shuffle: True
  train_ratio: 0.8
  architecture: BaseDataloader

model:
  name: klue/bert-base
  architecture: BaseModel

tokenizer:
  new_tokens: []
  new_special_tokens: []

train:
  max_epoch: 1
  batch_size: 64
  learning_rate: 1e-5
  loss: ce
  label_smoothing: 0.1
  use_frozen: False
  
utils:
  seed: 42
  monitor: val_f1
  patience: 25
  top_k: 3
  precision: 32 # default: 32. 16으로 하면 정확도를 포기하는 대신 훈련 속도 빨라짐.

k_fold:
  use_k_fold: False # KFold 사용 여부
  num_split: 5
  
wandb:
  team_account_name: next-level-potato # 팀 계정
  project_repo: RE  # 프로젝트 레포 이름
  name: kbh # 실험자 명
  info: baseline_bert-base # 실험명