path:
  train_path: ./data/raw_data/train.csv
  test_path: ./data/raw_data/train.csv
  predict_path: ./data/raw_data/test_data.csv
  save_path: saved_models/
  ckpt_path: # checkpoint path for resuming training

dataloader:
  shuffle: True
  train_ratio: 0.8
  swap: False
  architecture: MultipleHeadDataloader # ⭐

model:
  name: klue/bert-base
  architecture: MultipleHeadRobertaModel # ⭐

tokenizer:
  new_tokens: []
  new_special_tokens: []

train:
  max_epoch: 1
  batch_size: 64
  learning_rate: 1e-5
  loss: ce
  label_smoothing: 0.1
  use_frozen: False
  
utils:
  seed: 42
  monitor: val_f1
  patience: 25
  top_k: 3
  precision: 32 # 16 is also possible

k_fold:
  use_k_fold: False
  num_folds: 3
  num_splits: 5
  
wandb:
  team_account_name: next-level-potato # 팀 계정
  project_repo: RE  # 프로젝트 레포 이름
  name: lja # 실험자 명
  info: baseline_bert-base # 실험명
