wandb:
  team_account_name: nlp12 # 팀 계정 이름으로 바꿀 것 / 시험삼아 1차 팀 계정에 해봄
  project_repo: RE  # 프로젝트 레포 이름
  name: kbh # 실험자 명
  info: baseline_test # 실험명

path:
  train_path: ./data/raw_data/train.csv
  dev_path: ./data/raw_data/train.csv # train set에서 dev 파일 분리해서 만들고 수정할 것
  test_path: ./data/raw_data/test_data.csv

data:
  shuffle: True

model:
  name: klue/bert-base
  best_model_path: ./best_model

train:
  seed: 42
  checkpoints_dir : "./checkpoints"
  save_total_limits : 3
  save_steps : 500
  num_train_epochs : 3
  learning_rate : 5e-5
  train_batch_size : 16
  eval_batch_size : 16
  warmup_steps : 500
  weight_decay: 0.01
  logging_dir : "./logs"
  logging_steps : 100
  evaluation_strategy : "steps"
  eval_steps : 500
  load_best_model_at_end : True